3回目の課題提出（再提出）
Soysoy860/RaiseTech_task03-02 pull request #1
Opened 2022-08-07 02:43 UTC by Soysoy860

キー：科目　値：点数　のコレクションを作成。
コレクションにないキーを呼び出そうとするとExceptionが出て、
キーの一覧が出力される。

![raisetechTask03](https://user-images.githubusercontent.com/107778318/183272700-053f7aa2-3279-4ba1-a905-d88c59c58617.png)

2022-08-08 03:47 UTC, YudaiNoda3576 requested changes
コメントしました〜
`.idea`はGitHubで管理する必要はないので`.gitignore`をルートディレクトリ直下に新規作成して追記しておいてください〜

2022-08-08 03:47 UTC, YudaiNoda3576 commented on src/Main.java
> +        Map<String, Integer> score = new HashMap<>();
`subjectScoreMap` とかの方が適切かと思います！

2022-08-08 03:47 UTC, YudaiNoda3576 commented on src/Main.java
> +        } catch (Exception e) {
ここは`Exception`ではなく`IllegalArgumentException`の方が良いかもしれません！
Exceptionで全ての例外を受け取るよりも実装者が例外を自明なものとして考慮していることがコードから読み取れた方が良いと思うからです！

2022-08-08 03:47 UTC, YudaiNoda3576 commented on src/Main.java
> +                throw new Exception("指定した科目のスコアはありません");
メッセージが適切じゃない気がします・・・
指定した科目のスコアが無いのではなく、指定した科目が無いのでは。。。？

2022-08-08 12:50 UTC, Soysoy860 commented
@YudaiNoda3576 
> コメントしました〜 `.idea`はGitHubで管理する必要はないので`.gitignore`をルートディレクトリ直下に新規作成して追記しておいてください〜

→こちら、対応しました！
90e51f18946a59ebadc7162e98c25fa41a25a47b

他、変数名の変更、IllegalArgumentExceptionに修正、出力コメントも修正しました
c6dacb12a6ad760c7dffe3d0dc1f6d1b54b4b823


---------
変数名等もなかなかうまくつけられず、
細かくみていただいてありがとうございます。
お時間あるときに、ご確認よろしくおねがいします。

2022-08-10 01:08 UTC, YudaiNoda3576 commented
コミットにコメントしております「〜

2022-08-15 12:25 UTC, merged